default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin

development:
  <<: *default
  database: RubyBlog_development

test:
  <<: *default
  database: RubyBlog_test

production:
  <<: *default
  database: RubyBlog_production

# mysql
#default: &default
#  adapter: mysql2
#  encoding: utf8mb4
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password: "admin"
#  host: localhost

#development:
#  <<: *default
#  database: RubyBlog_development


#test:
#  <<: *default
#  database: RubyBlog_test


#production:
#  <<: *default
#  database: RubyBlog_production
#  username: RubyBlog
#  password: <%#= ENV["RUBYBLOG_DATABASE_PASSWORD"] %>

