default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT', 7418) %>

development:
  <<: *default
  database: RubyBlog_development

test:
  <<: *default
  database: RubyBlog_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
