default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: RubyBlog_development

test:
  <<: *default
  database: RubyBlog_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
